---
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.6
    hooks:
      - id: ruff
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.29.3
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.17.0
    hooks:
    - id: reorder-python-imports
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v4.0.0
    hooks:
    - id: add-trailing-comma
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.3.1
    hooks:
    - id: mypy
      additional_dependencies: [types-all]
